[book]
#  This book is called
title = "Command Line Applications in Rust"
# ...but friends call it "Clair"
authors = ["The Rust CLI Working Group"]
multilingual = false
src = "src"

[output.html]
curly-quotes = true
additional-css = ["src/special-content.css"]
